In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv
%matplotlib inline

In [3]:
#read in the data as pandas dataframes
county_facts = pd.read_csv("../data-jam-august-2016-master/csv/county_facts.csv")
primary_results = pd.read_csv("../data-jam-august-2016-master/csv/primary_results.csv")

In [4]:
candidates = list(primary_results.candidate.unique())
candidateDFs = {}
for politician in candidates:
    tempKey = politician.strip().lower().replace(' ', '_')
    tempResult = primary_results.iloc[:,3:][primary_results.iloc[:,3:].candidate==politician]
    candidateDFs[tempKey]= tempResult

In [5]:
complete_frame = county_facts

In [14]:
for politician in candidateDFs:
    tempDF = candidateDFs[politician].iloc[:,(0,3)]
    colnames = ['fips1']
    colnames.append(politician)
    tempDF.columns = colnames
    fips_series = tempDF.loc[:,'fips1'].dropna().astype('int').to_frame()
    fips_series.columns=['fips']
    tempDF = tempDF.join(fips_series).iloc[:,1:]
    complete_frame1 = pd.merge(complete_frame, tempDF, on=['fips'], how='left')
    complete_frame = complete_frame1

In [62]:
complete_frame.describe()

/Users/ylin11/Code/Sandbox/EverythingSandbox/lib/lib/python3.5/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,fips,Pop_2014_count,Pop_2010_base_count,Pop_change_pct,Pop_2010_count,Age_under_5_pct,Age_under_18_pct,Age_over_65_pct,Sex_female_pct,Race_white_pct,...,marco_rubio,ted_cruz,bernie_sanders_y,no_preference,ben_carson,donald_trump,rand_paul,chris_christie,john_kasich,jeb_bush
count,3195.000000,3.195000e+03,3.195000e+03,3195.000000,3.195000e+03,3195.000000,3195.000000,3195.000000,3195.000000,3195.000000,...,1890.000000,2711.000000,2798.000000,0.0,1022.000000,2711.000000,99.000000,99.000000,2711.000000,145.000000
mean,30358.079499,2.993963e+05,2.899137e+05,0.508545,2.899019e+05,5.900782,22.545290,17.524632,49.913271,84.953271,...,1650.413757,2714.800812,3692.927806,NaN,525.266145,4632.818886,85.646465,33.171717,1410.358539,435.179310
std,15181.225584,5.768468e+06,5.584181e+06,4.180066,5.583955e+06,1.211925,3.418896,4.433712,2.425066,16.290780,...,5111.611361,6242.384644,13059.531786,NaN,974.712369,9967.092053,203.405863,86.009496,4775.271461,1070.178695
min,0.000000,0.000000e+00,0.000000e+00,-17.000000,8.200000e+01,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,2.000000,1.000000,0.000000,2.000000
25%,18172.000000,1.113450e+04,1.129500e+04,-1.900000,1.129500e+04,5.200000,20.500000,14.700000,49.500000,80.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,29175.000000,2.655300e+04,2.644600e+04,-0.100000,2.642400e+04,5.800000,22.500000,17.200000,50.400000,91.900000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,45076.000000,7.247600e+04,7.150450e+04,2.300000,7.144800e+04,6.500000,24.200000,19.800000,51.100000,95.900000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,56045.000000,3.188571e+08,3.087581e+08,72.900000,3.087455e+08,13.700000,42.000000,52.900000,56.800000,99.300000,...,111898.000000,147721.000000,434656.000000,NaN,9945.000000,179130.000000,1633.000000,745.000000,101217.000000,6548.000000

In [20]:
frac_frame = county_facts
for politician in candidateDFs:
    tempDF = candidateDFs[politician].iloc[:,(0,4)]
    colnames = ['fips1']
    colnames.append(politician)
    tempDF.columns = colnames
    fips_series = tempDF.loc[:,'fips1'].dropna().astype('int').to_frame()
    fips_series.columns=['fips']
    tempDF = tempDF.join(fips_series).iloc[:,1:]
    frac_frame = pd.merge(frac_frame, tempDF, on=['fips'], how='left')

In [38]:
complete_frame.loc[:,("fips", "state_abbreviation", "area_name","Revenue_retail", 'Business_black_owned_pct')].to_csv(path_or_buf='vincent_try_1.csv')

In [43]:
dem_candidates = list(primary_results[primary_results.party=="Democrat"].candidate.unique())
rep_candidates = list(primary_results[primary_results.party=="Republican"].candidate.unique())

In [46]:
dem_frame = county_facts
for politician in dem_candidates:
    politician = politician.strip().lower().replace(' ', '_')
    tempDF = candidateDFs[politician].iloc[:,(0,3)]
    colnames = ['fips1']
    colnames.append(politician)
    tempDF.columns = colnames
    fips_series = tempDF.loc[:,'fips1'].dropna().astype('int').to_frame()
    fips_series.columns=['fips']
    tempDF = tempDF.join(fips_series).iloc[:,1:]
    complete_frame1 = pd.merge(dem_frame, tempDF, on=['fips'], how='left')
    dem_frame = complete_frame1

In [47]:
rep_frame = county_facts
for politician in rep_candidates:
    politician = politician.strip().lower().replace(' ', '_')
    tempDF = candidateDFs[politician].iloc[:,(0,3)]
    colnames = ['fips1']
    colnames.append(politician)
    tempDF.columns = colnames
    fips_series = tempDF.loc[:,'fips1'].dropna().astype('int').to_frame()
    fips_series.columns=['fips']
    tempDF = tempDF.join(fips_series).iloc[:,1:]
    complete_frame1 = pd.merge(rep_frame, tempDF, on=['fips'], how='left')
    rep_frame = complete_frame1

In [69]:
dem_winners = dem_frame.iloc[:,54:].idxmax(axis=1).to_frame()
dem_winners.columns = ['dem_winners']
dem_frame = dem_frame.join(dem_winners)

In [71]:
rep_winners = rep_frame.iloc[:,54:].idxmax(axis=1).to_frame()
rep_winners.columns = ['rep_winners']
rep_frame = rep_frame.join(rep_winners)

In [94]:
fips_winner_frame = pd.merge(rep_frame.iloc[:,(0,65)], dem_frame.iloc[:,(0,59)], on=['fips'])
master_winner_frame = pd.merge(fips_winner_frame, county_facts, on=['fips'])

In [102]:
pd.crosstab(master_winner_frame.dem_winners, master_winner_frame.state_abbreviation)

state_abbreviation,AL,AR,AZ,CA,CO,DE,FL,GA,HI,IA,...,SC,SD,TN,TX,UT,VA,WA,WI,WV,WY
dem_winners,,,,,,,,,,,,,,,,,,,,,
bernie_sanders,0,2,1,20,51,0,9,1,4,40,...,0,25,3,15,29,16,39,71,55,18
hillary_clinton,67,73,14,38,13,3,58,158,0,59,...,46,41,92,239,0,117,0,1,0,5

In [104]:
master_winner_frame.to_csv(path_or_buf="master-with-winner.csv")